apiVersion: v1
kind: Pod
metadata:
  name: pod-nginx
  annotations: 
    app: demo
  labels:
    tyre: app
    role: master
  namespace: default
spec:
  containers:
  - name: pod-nginx-container
    image: nginx:latest
    imagePullPolicy: IfNotPresent
    workingDir: /root
    ports:
    - name: nginx-port
      containerPort: 80
      hostIP: 0.0.0.0
      hostPort: 80
      protocol: TCP
    resources:
      limits:
        memory: "200Mi"
        cpu: 1.5
      requests:
        memory: "100Mi"
        cpu: 1
  restartPolicy: Always      
  hostname: pod-demo
  nodeName: k8s-master
  nodeSelector:
    kubernetes.io/hostname: k8s-master



#lifecycle
#livenessProbe
#readinessProbe    