apiVersion: v1
kind: Pod
metadata:
  name: poststart-pod
  namespace: default
spec:
  containers:
  - name: busybox-httpd
    image: busybox:latest
    imagePullPolicy: IfNotPresent
    command: ["/bin/httpd", "-f", "-h /tmp"]
    lifecycle:
      postStart:
        exec:
          command: ["/bin/sh", "-c",  "echo home >> /tmp/index.html"]
  nodeSelector:
   node.role: master