apiVersion: apps/v1
kind: Deployment
metadata: 
  name: myapp-deploy
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
      release: stable
  template: 
    metadata:
      name: myapp-pod
      labels:
        release: stable
        app: myapp
    spec:
      containers:
      - name: myapp-container
        image: ikubernetes/myapp:v1
        ports:
          - name: http
            containerPort: 80
              
---
apiVersion: v1
kind: Service
metadata: 
  name: myapp-svc
  namespace: default
spec: 
  selector:
    app: myapp
  type: ClusterIP
  ports:
  - name: myapp
    port: 80
    targetPort: 80
