apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: myapp-daemonset
  namespace: default
spec:
  selector: 
    matchLabels:
      app: filebeat
      release: stable
  template:
    metadata:
      app: fliebeat
      release: stable
  spec:
    containers:
    - name: filebeat
      image: ikuberneters/filebeat:5.6.5-alpine
      env:
      - name: REDIS_HOST
        value: redis.default.svc.cluster.local
      - name: REDIS_LOG_LEVEL
        value: info