apiVersion: apps/v1
kind: Deployment
metadata: 
  name: myapp-deploy
  namespace: default
spec:
  replicas: 2
    matchLabels:
      app: myapp
      release: stable
  template: 
    metadata:
      name: myapp-pod
      release: stable
      env: test
    spec:
      containers:
      - name: myapp-container
        image: ikubernetes/myapp:v1
        ports:
          - name: http
            containerPort: 80
              