apiVersion: apps/v1
kind: ReplicaSet
metadata: 
  name: rs-demo
  namespace: default
spec:
  replicas: 2
  minReadySeconds: 10
  selector:
    matchLabels:
      app: myapp
      release: stable
  template: 
    metadata:
      name: myapp-pod
      labels:
        app: myapp
        release: stable
    spec:
      containers:
      - name: myapp-container
        image: ikubernetes/myapp:v1
        ports:
          - name: http
            containerPort: 80
            